# **Project 1 - Sales Analysis - ETL**

## Objectives

- Extract data from provided CSV files
- Clean it 
- Apply feature engineering if necessary 
- Remove any unnecessary columns
- Save to a new CSV file


## Inputs

CSV files provided:

stores data-set.csv
sales data-set.csv
features data set.csv

Renamed files to a uniform naming convention:

Sales_Features_DataSet.csv
Sales_DataSet.csv
Sales_Stores_DataSet.csv

Note: original files are stored in Data/OriginalFiles


## Outputs

CSV file created from ETL etc stored in Data:

Sales_Combined.csv



## Additional Comments

Had an error trying to use pip install - r requirements.txt 

So initally manually installed:

numpy
pandas
seaborn
plotly
seaborn
matplotlib

THEN after checking with course fascilitator needed to remove ppscore from the requirements.txt file
This produced another error which I tracked down to being ydata-profiling so removed that as well
Re-installed dependancies from the requirements.txt file - works fine.

## Initalise Working Environment

In [7]:
#import libraries
import os
import numpy as np
import pandas as pd

# Section 1 - Initalisation

## Intitialise All Variables To Be Used In Global Stack

In [8]:
#DataFrame vars for ETL
dfSales_Features_DataSet = None
dfSales_Stores_DataSet = None
dfSales_DataSet = None
dfSales_Combined_DataSet = None
dfTemp = None

#stores current directory
strCurrentDir = ""

#constant for project directory
CNST_STR_PROJECT_DIR = "Project1-SalesAnalysis"

#file path constants
CNST_STR_SALESCOMBINEDFILEPATH = "/Data/VisualisationDataSet/Sales_Combined_DataSet.csv"
CNST_STR_SALESFILEPATH = "/Data/CleanedDataSets/Sales_DataSet_Cleaned.csv"
CNST_STR_SALESFEATURESFILEPATH = "/Data/CleanedDataSets/Sales_Features_DataSet_Cleaned.csv"
CNST_STR_SALESSTORESFILEPATH = "/Data/CleanedDataSets/Sales_Stores_DataSet_Cleaned.csv"

#other vars
objColumns = None
lstColumns = []
dictColumns = {}

## Set Current Directory To Base Project Directory

In [9]:
#get project directory - default is jupyter notebook sub folder as that is where this file is located!
#so move back one to the project root path
# Source - https://stackoverflow.com/a/17726833
# Posted by chimpsarehungry
# Retrieved 2026-07-05, License - CC BY-SA 3.0

#get current folder
strCurrentDir = os.getcwd()

#is the last part of the path the project directory?
if not strCurrentDir.endswith(CNST_STR_PROJECT_DIR):
   #get current working directory and move back one to the project root path
   strCurrentDir =  os.path.normpath(os.getcwd() + os.sep + os.pardir)
   os.chdir(os.path.dirname(strCurrentDir))
   #change directory
   os.chdir(strCurrentDir)

#confirm current directory is project directory
print(f"Current Directory: \n {os.getcwd()}")

Current Directory:
 /Users/rogerwilliams/Projects/Python/CourseProjects/Project1-SalesAnalysis

# Section 1 - Combination

- Read csv files
- Combine into one DataFrame

## Read csv Files Into Variable For Processing

In [10]:
#read csv files into DataFrames
dfSales_Features_DataSet = pd.read_csv(strCurrentDir + CNST_STR_SALESFEATURESFILEPATH)
dfSales_DataSet = pd.read_csv(strCurrentDir + CNST_STR_SALESFILEPATH)
dfSales_Stores_DataSet = pd.read_csv(strCurrentDir + CNST_STR_SALESSTORESFILEPATH)

## Combine The Data Frames!

## How The DataFrames Are Related

_"primary key"_  
dfSales_Stores_DataSet Has One Common Column: Store  
dfSales_DataSet Has One Common Column With dfSales_Stores_DataSet: Store  
dfSales_Features_DataSet Has One Common Column With dfSales_Stores_DataSet: Store  

_Columns Shared Between dfSales_DataSet And dfSales_Features_DataSet:_    
Store, Date

Combined Columns To Use For Analysis:  
Store: int64
Date: datetime64[us]
Size: int64
Temperature: float64
Dept: int64
Weekly_Sales: float64
IsHoliday: bool
MarkDown1: float64
MarkDown2: float64
MarkDown3: float64
MarkDown4: float64
MarkDown5: float64
StoreType: int64 <- Feature Engineering addition to Sales_Stores_DataSet.csv>

In [11]:
#first convert the Date columns to datetime format
dfSales_DataSet["Date"] = pd.to_datetime(dfSales_DataSet["Date"], format="%d/%m/%Y")
dfSales_Features_DataSet["Date"] = pd.to_datetime(dfSales_Features_DataSet["Date"], format="%d/%m/%Y")

# combine DataFrames
dfSales_Combined_DataSet = pd.merge(dfSales_DataSet, dfSales_Features_DataSet, on=['Store', 'Date'], how='inner')

# Merge Sales and Features
dfSales_Combined_DataSet = pd.merge(
    dfSales_DataSet,
    dfSales_Features_DataSet,
    on=["Store", "Date"],
    how="inner",
    indicator = True
)

# Merge the result with Stores

dfSales_Combined_DataSet = pd.merge(
    dfSales_Combined_DataSet,
    dfSales_Stores_DataSet,
    on="Store",
    how="inner"
)

#show results
dfSales_Combined_DataSet.tail(100)

,Store,Date,Weekly_Sales,IsHoliday_x,Temperature,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,IsHoliday_y,_merge,Unnamed: 0,Size,StoreType
421470,45,2012-10-19,2274.09,False,56.47,2004.02,0.00,3.18,437.73,1537.49,False,both,44,118221,2
421471,45,2012-10-19,1119.59,False,56.47,2004.02,0.00,3.18,437.73,1537.49,False,both,44,118221,2
421472,45,2012-10-19,54427.64,False,56.47,2004.02,0.00,3.18,437.73,1537.49,False,both,44,118221,2
421473,45,2012-10-19,38408.23,False,56.47,2004.02,0.00,3.18,437.73,1537.49,False,both,44,118221,2
421474,45,2012-10-19,2125.11,False,56.47,2004.02,0.00,3.18,437.73,1537.49,False,both,44,118221,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,2012-10-26,2487.80,False,58.85,4018.91,58.08,100.00,211.94,858.33,False,both,44,118221,2
421566,45,2012-10-26,5203.31,False,58.85,4018.91,58.08,100.00,211.94,858.33,False,both,44,118221,2
421567,45,2012-10-26,56017.47,False,58.85,4018.91,58.08,100.00,211.94,858.33,False,both,44,118221,2
421568,45,2012-10-26,6817.48,False,58.85,4018.91,58.08,100.00,211.94,858.33,False,both,44,118221,2
421569,45,2012-10-26,1076.80,False,58.85,4018.91,58.08,100.00,211.94,858.33,False,both,44,118221,2

## Observations - Sales_Combined_DataSet

Checks:

Checked Column value change for Markdown1 at page: 81 to check if had value: 10382.9
as per the raw csv file.

Checked column value change for Store at page: 2049 to check if StoreType column
was correctly showing the value 2 when the Store column value was 3 as in the 
dfSales_Store_DataSet DataFrame Store value 3 = store type B which in the new column
added during data transformation in Notebook_ETL_Sales_Stores_DataSet.ipynb is 2

All values found as expected.

Note: In Features data set.csv there is 7 months f data NOT in sales data-set.csv so needed 
      to filter that out of the results

## Observations - Sales_Combined_DataSet
Check new DataFrame schema

In [12]:
#check new DataFrame schema
dfSales_Combined_DataSet.dtypes

Store                    int64
Date            datetime64[ns]
Weekly_Sales           float64
IsHoliday_x               bool
Temperature            float64
MarkDown1              float64
MarkDown2              float64
MarkDown3              float64
MarkDown4              float64
MarkDown5              float64
IsHoliday_y               bool
_merge                category
Unnamed: 0               int64
Size                     int64
StoreType                int64
dtype: object

## Observations - Sales_Combined_DataSet

Columns count correct, need to rename some delete others before visualisation

---

# Section 2 - Transformation

- Delete unnecessary columns
- Rename any columns if necessary

Columns to renove (All created by Pandas merge method):
_merge
IsHoliday_y
Unnamed: 0 


Columns To Rename:
IsHoliday_x -> IsHoliday

In [13]:
#delete unnecessary columns  
dfSales_Combined_DataSet.drop(columns=["_merge", "IsHoliday_y", "Unnamed: 0"], inplace=True)

#check results
dfSales_Combined_DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Date          421570 non-null  datetime64[ns]
 2   Weekly_Sales  421570 non-null  float64
 3   IsHoliday_x   421570 non-null  bool
 4   Temperature   421570 non-null  float64
 5   MarkDown1     421570 non-null  float64
 6   MarkDown2     421570 non-null  float64
 7   MarkDown3     421570 non-null  float64
 8   MarkDown4     421570 non-null  float64
 9   MarkDown5     421570 non-null  float64
 10  Size          421570 non-null  int64
 11  StoreType     421570 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(7), int64(3)
memory usage: 35.8 MB

## Observations - Combined_DataSet

Schema as eExpected

## Observations - Rename Columns

In [14]:
#rename columns: IsHoliday_x -> IsHoliday StoreType -> Store_Type  Size_x -> Store_Size
dfSales_Combined_DataSet.rename(columns={'IsHoliday_x': 'IsHoliday', 'StoreType': 'Store_Type', 'Size': 'Store_Size'}, inplace=True)

#check results
dfSales_Combined_DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Date          421570 non-null  datetime64[ns]
 2   Weekly_Sales  421570 non-null  float64
 3   IsHoliday     421570 non-null  bool
 4   Temperature   421570 non-null  float64
 5   MarkDown1     421570 non-null  float64
 6   MarkDown2     421570 non-null  float64
 7   MarkDown3     421570 non-null  float64
 8   MarkDown4     421570 non-null  float64
 9   MarkDown5     421570 non-null  float64
 10  Store_Size    421570 non-null  int64
 11  Store_Type    421570 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(7), int64(3)
memory usage: 35.8 MB

## Observations - Combined_DataSet

Schema as expected

## Check For Missing Values (Paranoia)

In [15]:
#get total missing values
intMissing = dfSales_Combined_DataSet.isnull().sum()

#calculate percent missing
intMissingPercent = ( intMissing / len(dfSales_Combined_DataSet) * 100)
dfCheck = pd.DataFrame( {"Missing Values": intMissing, "%" : intMissingPercent})

#show results
if dfCheck["Missing Values"].sum() !=0:
   print( dfCheck[dfCheck["Missing Values"] > 0])
else:
   print( "No Missing Values")

No Missing Values

## Observations - Combined_DataSet

No Missing Values - Phew!

---

## Data Transformations/Feature Engineering

Had Mad Scientist idea:

Create a column with just year and month in it, if i get time (and if its actually feasible)
Might be able to knock some visualsations by month...

In [16]:
#create a column with JUST year and month as integer
dfSales_Combined_DataSet["YearMonth"] = dfSales_Combined_DataSet["Date"].dt.strftime('%Y%m').astype(int)

#check results
dfSales_Combined_DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Date          421570 non-null  datetime64[ns]
 2   Weekly_Sales  421570 non-null  float64
 3   IsHoliday     421570 non-null  bool
 4   Temperature   421570 non-null  float64
 5   MarkDown1     421570 non-null  float64
 6   MarkDown2     421570 non-null  float64
 7   MarkDown3     421570 non-null  float64
 8   MarkDown4     421570 non-null  float64
 9   MarkDown5     421570 non-null  float64
 10  Store_Size    421570 non-null  int64
 11  Store_Type    421570 non-null  int64
 12  YearMonth     421570 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(7), int64(4)
memory usage: 39.0 MB

## Observations - Combined_DataSet

Schema as expected

## Check Data In New Column

In [17]:
#check data
dfSales_Combined_DataSet.head(50)

,Store,Date,Weekly_Sales,IsHoliday,Temperature,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,Store_Size,Store_Type,YearMonth
0,1,2010-02-05,24924.50,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
1,1,2010-02-05,50605.27,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
2,1,2010-02-05,13740.12,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
3,1,2010-02-05,39954.04,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
4,1,2010-02-05,32229.38,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
5,1,2010-02-05,5749.03,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
6,1,2010-02-05,21084.08,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
7,1,2010-02-05,40129.01,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
8,1,2010-02-05,16930.99,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
9,1,2010-02-05,30721.50,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
10,1,2010-02-05,24213.18,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
11,1,2010-02-05,8449.54,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
12,1,2010-02-05,41969.29,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
13,1,2010-02-05,19466.91,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
14,1,2010-02-05,10217.55,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
15,1,2010-02-05,13223.76,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
16,1,2010-02-05,4729.50,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
17,1,2010-02-05,1947.05,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
18,1,2010-02-05,5034.10,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
19,1,2010-02-05,8907.63,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
20,1,2010-02-05,13623.98,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
21,1,2010-02-05,24146.49,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
22,1,2010-02-05,8272.90,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
23,1,2010-02-05,11609.50,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
24,1,2010-02-05,11737.12,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
25,1,2010-02-05,2293.00,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
26,1,2010-02-05,1085.29,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
27,1,2010-02-05,7024.95,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
28,1,2010-02-05,5491.00,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
29,1,2010-02-05,3455.92,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
30,1,2010-02-05,11875.84,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
31,1,2010-02-05,8589.77,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
32,1,2010-02-05,14350.83,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
33,1,2010-02-05,2770.00,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
34,1,2010-02-05,120.00,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
35,1,2010-02-05,3438.16,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
36,1,2010-02-05,115564.35,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
37,1,2010-02-05,66780.63,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
38,1,2010-02-05,1011.83,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
39,1,2010-02-05,8366.71,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
40,1,2010-02-05,4674.75,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
41,1,2010-02-05,37.44,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
42,1,2010-02-05,20837.77,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
43,1,2010-02-05,70.00,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
44,1,2010-02-05,814.00,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
45,1,2010-02-05,11501.46,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
46,1,2010-02-05,1.16,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
47,1,2010-02-05,3508.04,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
48,1,2010-02-05,439.00,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002
49,1,2010-02-05,21249.31,False,42.31,0.0,0.0,0.0,0.0,0.0,151315,1,201002

## Observations - Combined_DataSet

Data as expected

## Save Combined DataFrame To CSV File

In [18]:
#save dfCombined_DataSet to csv file with chatGPT suggested options
dfSales_Combined_DataSet.to_csv(strCurrentDir + CNST_STR_SALESCOMBINEDFILEPATH, date_format="%d/%m/%Y")

# Next Steps

End of ETL process. Now visualising the hypothesis can begin!

See notebook:
Notebook_Visualisations.jpynb